# Generated by Django 6.0.6 on 2026-06-10 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_offre', models.CharField(choices=[('offre', 'Offre (je propose mon aide)'), ('demande', 'Demande (je cherche un mentor)')], max_length=10)),
                ('format', models.CharField(choices=[('présentiel', 'Présentiel'), ('en ligne', 'En ligne'), ('les deux', 'Les deux')], max_length=12)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermée', 'Fermée')], default='ouverte', max_length=10)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='users.competence')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('statut', models.CharField(choices=[('proposé', 'Proposé'), ('accepté', 'Accepté'), ('refusé', 'Refusé')], default='proposé', max_length=10)),
                ('date_matching', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings_mentore', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='matching.offrementorat')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('mentor', models.F('mentore')), _negated=True), name='mentor_diff_mentore')],
            },
        ),
    ]
